# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 13:38
from __future__ import unicode_literals

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetOdds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_created', models.DateTimeField(auto_now_add=True)),
                ('odds', django_mysql.models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_club_name', models.CharField(max_length=200)),
                ('cn_club_name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=200)),
                ('cn_name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
