# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 10:48
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='betodds',
            name='club_rumors',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
